import "../styles/globals.css";
import type { AppProps } from "next/app";
import { CssBaseline } from "@mui/material";
import Head from "next/head";
import { ThemeProvider } from "@mui/material/styles";
import darkTheme from "../styles/darkTheme";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>LeagueCalc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={darkTheme}>
        <CssBaseline />
        {/* eslint-disable-next-line react/jsx-props-no-spreading */}
        <Component {...pageProps} />
      </ThemeProvider>
    </>
  );
}

export default MyApp;
